name: Tests via Moodle CI framework

on:
  push:
  pull_request:
  schedule:
    # Weekly, @ 00:00 on Sunday (UTC).
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        # Cannot test with PHP 7.0 any more because PHPUnit 8 is now using the ':void' return type
        # on all template methods, supported on 7.1+.
        # Note that, still, the plugin will work OK, it's just the PHPUnit tests which cannot
        # be executed with that PHP version - though at some point in the future some regressions could exist ;).
        php: ['7.1', '7.2', '7.3', '7.4']
        moodle-branch: [
            'MOODLE_34_STABLE', 'MOODLE_35_STABLE', 'MOODLE_36_STABLE', 'MOODLE_37_STABLE',
            'MOODLE_38_STABLE', 'MOODLE_39_STABLE', 'MOODLE_310_STABLE', 'MOODLE_311_STABLE', 'master'
        ]
        database: ['mariadb']
        php-ini-values: ['']
        exclude:
          # PHP 7.1 support since Moodle 3.7+.
          # Moodle 3.9+ requires PHP 7.2+.
          - { php: '7.1', moodle-branch: 'MOODLE_39_STABLE',  database: mariadb }
          - { php: '7.1', moodle-branch: 'MOODLE_310_STABLE', database: mariadb }
          - { php: '7.1', moodle-branch: 'MOODLE_311_STABLE', database: mariadb }
          - { php: '7.1', moodle-branch: 'master',            database: mariadb }
          # Moodle 3.11+ requires PHP 7.3+.
          - { php: '7.2', moodle-branch: 'MOODLE_311_STABLE', database: mariadb }
          - { php: '7.2', moodle-branch: 'master',            database: mariadb }
          # PHP 7.3 support since Moodle 3.6.4+.
          - { php: '7.3', moodle-branch: 'MOODLE_34_STABLE',  database: mariadb }
          - { php: '7.3', moodle-branch: 'MOODLE_35_STABLE',  database: mariadb }
          # PHP 7.4 support since Moodle 3.8.3+.
          - { php: '7.4', moodle-branch: 'MOODLE_34_STABLE',  database: mariadb }
          - { php: '7.4', moodle-branch: 'MOODLE_35_STABLE',  database: mariadb }
          - { php: '7.4', moodle-branch: 'MOODLE_36_STABLE',  database: mariadb }
          - { php: '7.4', moodle-branch: 'MOODLE_37_STABLE',  database: mariadb }
        include:
          # Tests latest Moodle versions under 'pgsql' too.
          - { php: '7.4', moodle-branch: 'MOODLE_310_STABLE', database: pgsql }
          - { php: '7.4', moodle-branch: 'MOODLE_311_STABLE', database: pgsql }
          - { php: '7.4', moodle-branch: 'master',            database: pgsql }
          # PHP 8.0 support since Moodle 3.11+:
          # - minimum 'max_input_vars' requirement for PHP 8.0. Ref.: MDL-71390
          - { php: '8.0', moodle-branch: 'MOODLE_311_STABLE', database: pgsql, php-ini-values: 'max_input_vars=5000' }
          - { php: '8.0', moodle-branch: 'master',            database: pgsql, php-ini-values: 'max_input_vars=5000' }

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd, mbstring, mysqli, pgsql, soap, xmlrpc, zip
          ini-values: ${{ matrix.php-ini-values }}
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Moodle PHPDoc Checker
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit

      - name: Behat features
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome
